# Generated by Django 4.2.9 on 2024-02-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=150, verbose_name='Введите почту')),
                ('telephone', models.IntegerField(verbose_name='Введите номер телефона')),
                ('age', models.IntegerField(verbose_name='Введите дату рождения')),
                ('username', models.CharField(max_length=50, verbose_name='Придумайте ник')),
                ('password', models.CharField(max_length=50, verbose_name='Введите пароль')),
                ('password2', models.CharField(max_length=50, verbose_name='Повторите пароль')),
            ],
        ),
    ]
