# Generated by Django 4.2.9 on 2024-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='фото')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.CharField(max_length=250, verbose_name='описание')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('size', models.CharField(max_length=15, verbose_name='размер')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
